Last login: Sat Sep 30 21:59:20 on ttys001 Max-iMac:~ maxwinkler$ cd inlinesanctipetri Max-iMac:inlinesanctipetri maxwinkler$ git status On branch 2018 Your branch is up-to-date with 'origin/2018'. Changes not staged for commit:   (use "git add/rm <file>..." to update what will be committed)   (use "git checkout -- <file>..." to discard changes in working directory)
	deleted:    LICENSE
	modified:   README.md
	modified:   competiciones/alevin.html
	modified:   competiciones/benjamin.html
	modified:   competiciones/index.html
	modified:   competiciones/infantil.html
	modified:   competiciones/liga-sur.html
	modified:   competiciones/senior.html
	modified:   css/main.css
	modified:   demo.html
	modified:   demo2.html
	modified:   escuelas.html
	modified:   index.html
	deleted:    noticias.html
	modified:   nuestro-equipo/index.html
	deleted:    quienes-somos.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	LICENSE.txt
	blog/
	fbscript.js

no changes added to commit (use "git add" and/or "git commit -a")
Max-iMac:inlinesanctipetri maxwinkler$ git commit -a
Aborting commit due to empty commit message.
Max-iMac:inlinesanctipetri maxwinkler$ git commit -
error: pathspec '-' did not match any file(s) known to git.
Max-iMac:inlinesanctipetri maxwinkler$ git commit -a

modified:   README.md
modified:   competiciones/alevin.html
modified:   competiciones/benjamin.html
modified:   competiciones/index.html
modified:   competiciones/infantil.html
modified:   competiciones/liga-sur.html
modified:   competiciones/senior.html
modified:   css/main.css
modified:   escuelas.html
modified:   index.html
deleted:    noticias.html
modified:   nuestro-equipo/index.html
deleted:    quienes-somos.html
Nuevos cambios en todos los lados.
1. Footer terminado
2. Efecto hover añadido al nav
3. Terminado "Nuestro equipo" con select
4. Configurado el blog
5. * *Pending Approval** Cambio tamaño facebook widget

:q
:w